### ISSUE TITLE
Replace formspree contact us form with Zoho Bigin Webform

### ISSUE THREAD

**Issue by renjithbz** [renjithbz/boonze#1]
Formspree free version is not providing captcha support, receiving too many junk emails. Replace Formspree "contact us" form with Zoho Bigin web form. Attaching both HTML and JavaScript snippet of the Zoho Bigin web form. Feel free to use the appropriate one.
[Zoho-Bigin-Web-Form-HTML-Source-Code.txt](https://github.com/renjithbz/boonze/files/6795486/Zoho-Bigin-Web-Form-HTML-Source-Code.txt)
[Zoho-Bigin-Web-Form-JavaScript.txt](https://github.com/renjithbz/boonze/files/6795487/Zoho-Bigin-Web-Form-JavaScript.txt)

**Comment by tfsomrat** [comment]
I have added it, can you check?

**Comment by renjithbz** [comment]
Dear Somrat,

Excellent! Thank you for fixing this issue. I tested and it is working as expected. 

Thank you!
Renjith

**Comment by renjithbz** [comment]
Contact us form on the Boonze website is working as expected.
